### ISSUE TITLE
laravel 5.5 compatibiliy

### ISSUE THREAD

**Issue by Zae** [barryvdh/laravel-omnipay#19]
Hey Barry,

I'd like to use your package with laravel 5.5 and hopefully 5.6 very quicky, but there doesn't seem to be a stable version for 5.5 yet.

Is it possible to tag the current dev version or are there some things not working correctly yet?

Gr,
Ezra

**Comment by pinguinjkeke** [comment]
It works with laravel 5.5 if you select ```symfony/event-dispatcher@^2.8``` as dependency.

Laravel 5.6 switched to Symfony 4 components and it's no longer working :(

**Comment by barryvdh** [comment]
Omnipay v3 will support this.
