### ISSUE TITLE
laravel 6 support?

### ISSUE THREAD

**Issue by Zae** [barryvdh/laravel-omnipay#27]
Hi Barry,

Do you have any plans to support laravel 6 with this package?

**Comment by barryvdh** [comment]
sure make a PR

**Comment by Zae** [comment]
cool, I'll try soon(ish), I already have an active fork for the `omnipay/common 2` version of the package that I'm using so I need to figure out how :)

**Comment by sethsahin** [comment]
@barryvdh can i use with laravel 6 now?

**Comment by barryvdh** [comment]
Yeah 6 and 7
