### ISSUE TITLE
publish issue laravel 6.2

### ISSUE THREAD

**Issue by sethsahin** [barryvdh/laravel-omnipay#32]
when i try to vendor:publish givin me this error

"Unable to locate publishable resources."

**Comment by HamzaDus** [comment]
Only solution is to copy the config manually?

**Comment by chaiwei** [comment]
I am using laravel 5.8, tried with php artisan vendor:publish --provider="Barryvdh\Omnipay\ServiceProvider" it seems it is working fine.

**Comment by HamzaDus** [comment]
hmm, i've tried that too but that was not working as i far as i can remember. Btw, this
https://github.com/barryvdh/laravel-omnipay/commit/ea17a4def83b287ac86ce1d7b3e8d2cd61f97302
maybe the issue. The double quotes were missing before i think, anyway i ended copying it manually, to anyone who tries it later, please leave a comment if it does the trick for you.

**Comment by MattThurling** [comment]
Had the same problem as @HamzaDus when trying to publish using Laravel 7. Fixed by adding double quotes, as per @chaiwei

**Comment by sprklinginfo** [comment]
had the same issue in laravel  7.  so I tried to add double quotes as below and it worked:
$ php artisan vendor:publish --provider="Barryvdh\Omnipay\ServiceProvider"

Maybe the readme file should be corrected.

**Comment by sethsahin** [comment]
@sprklinginfo yes its work. /close
