### ISSUE TITLE
does not support laravel 8

### ISSUE THREAD

**Issue by parmonov98** [barryvdh/laravel-omnipay#36]
`composer require barryvdh/laravel-omnipay`
Using version ^0.2.2 for barryvdh/laravel-omnipay
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for barryvdh/laravel-omnipay ^0.2.2 -> satisfiable by barryvdh/laravel-omnipay[v0.2.2].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

Installation failed, reverting ./composer.json to its original content.

I downgraded and it required to install Laravel 7.

**Comment by barryvdh** [comment]
Tagged a new release
