### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by siarheipashkevich** [barryvdh/laravel-omnipay#37]
Please make a new release with laravel 8 supporting.

**Comment by bsormagec** [comment]
@barryvdh can you release laravel 8 version ?

**Comment by Luigidefra** [comment]
i follow

**Comment by benpoulson** [comment]
Use `composer require barryvdh/laravel-omnipay dev-master` for now, until a new release is cut.

**Comment by basepack** [comment]
@barryvdh are you reading this?

**Comment by barryvdh** [comment]
Yes tagged a new release.
