### ISSUE TITLE
Gateway configuration should use the name instead of the classname

### ISSUE THREAD

**Issue by dpgover** [barryvdh/laravel-omnipay#8]
GatewayManager, line 50:

``` php
if(!isset($this->gateways[$class])){
            $gateway = $this->factory->create($class, null, $this->app['request']);
            $gateway->initialize($this->getConfig($class));
            $this->gateways[$class] = $gateway;
        }
```

The config gets checked for the classname instead of the gateways name. I think it should be:

``` php
if(!isset($this->gateways[$class])){
            $gateway = $this->factory->create($class, null, $this->app['request']);
            $gateway->initialize($this->getConfig($gateway->getName()));
            $this->gateways[$class] = $gateway;
        }
```

That way, I can pass a custom gateway without having to use the fully qualified name of the class on the config file...

Am I correct?

Thanks

**Comment by siarheipashkevich** [comment]
@barryvdh what do you think about @dpgover solution?

**Comment by barryvdh** [comment]
Think so indeed

**Comment by siarheipashkevich** [comment]
@barryvdh may I create a PR with this changes?

**Comment by barryvdh** [comment]
Sure

**Comment by siarheipashkevich** [comment]
@barryvdh please see [PR](https://github.com/barryvdh/laravel-omnipay/pull/18)

**Comment by ammonkc** [comment]
@barryvdh @siarheipashkevich this [PR](https://github.com/barryvdh/laravel-omnipay/pull/18) seems to break the default gateway configs. see my [comment](https://github.com/barryvdh/laravel-omnipay/pull/18#issuecomment-388961127) here.

**Comment by barryvdh** [comment]
Reverted
