### ISSUE TITLE
Difference between Ignited's laravel-omnipay and this one

### ISSUE THREAD

**Issue by DMeganoski** [barryvdh/laravel-omnipay#9]
I'm just curious, it seems that ignited's version existed (slightly) before yours, and doesn't seem that this is a branch of ignited/omnipay, but seems to have similar functionality.

Both are a couple years old, and are still being updated with the laravel versions. 

So, I'm curious what the differences are / reason for creating a separate package. I've been working with laravel for a couple years now, and am a big fan of your work. I'd honestly rather depend on your package if there were reason to.

**Comment by barryvdh** [comment]
Not really sure, I either didn't know about it when I started this, or wasn't happy with the structure of it at the time. But haven't looked at either lately, I prefer to use omnipay directly.

**Comment by DMeganoski** [comment]
Sorry, you had responded just after I had started my vacation and it seems it had slipped my mind. 

I can completely understand that. Convenience is usually a sacrifice to functionality. I was just curious. 

I'll go ahead and close this.
